<section id="about" class="color-light text-center">
    <div class="container">
        <div class="divide40"></div>
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center">
                    <span class="bigintro">Quem sou?</span>
                </h2>
            </div>
        </div>
        <div class="divide20"></div>
        <div class="row">
            <div class="col-md-12 about">
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, isn't anything embarrassing hidden in the middle of text. </p><p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from injected humour, or non-characteristic words etc. </p>
            </div>
        </div>
    </div>
    <div class="divide40"></div>
</section>