<section id="parallax-3" data-type="background" data-speed="10" class="pages text-center">
    <div class="parallax-overlay">
        <section id="contact">
            <section class="container">
                <div class="divide40"></div>
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="text-center">
                            <span class="bigintro-light">Entre em Contato</span>
                        </h2>
                    </div>
                </div>
                <div class="divide20"></div>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3 form-input">
                        <input id="company" type="text" placeholder="Empresa" value="" name="company"/>
                    </div>
                    <div class="col-md-6 col-md-offset-3 form-input">
                        <input id="title" type="text" placeholder="Titulo" value="" name="title"/>
                    </div>
                    <div class="col-md-6 col-md-offset-3 form-input">
                        <input id="name" type="text" placeholder="Nome" value="" name="name"/>
                    </div>
                    <div class="col-md-6 col-md-offset-3 form-input">
                        <input id="email" type="email" placeholder="Email" value="" name="email"/>
                    </div>
                    <div class="col-md-6 col-md-offset-3 form-input">
                        <textarea id="message"  placeholder="Mensagem" name="message"></textarea>
                    </div>
                    <div class="col-md-6 col-md-offset-3 form-submit">
                        <button id="submit" class="btn btn-warning btn-lg" type="submit">Enviar</button>
                    </div>
                </div>
                <div class="divide60"></div>
            </section>
        </section>
    </div>
</section>