<section id="features" class="color-light">
    <div class="container">
        <div class="divide40"></div>
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center">
                    <span class="bigintro">Desenvolvimento</span>
                </h2>
            </div>
        </div>
        <div class="divide60"></div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="feature">
                    <i class="extralarge fa fa-bar-chart-o"></i>
                    <br/><br/>
                    <h3>Gerenciadores</h3>
                    <br/>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="feature">
                    <i class="extralarge fa fa-video-camera"></i>
                    <br/><br/>
                    <h3>Mídias</h3>
                    <br/>
                    <p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. </p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="feature">
                    <i class="extralarge fa fa-bullhorn"></i>
                    <br/><br/>
                    <h3>Publicidade</h3>
                    <br/>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="feature">
                    <i class="extralarge fa fa-picture-o"></i>
                    <br/><br/>
                    <h3>Design</h3>
                    <br/>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
                </div>
            </div>
        </div>
        <div class="divide60"></div>
    </div>
</section>