<section id="parallax-1" data-type="background" data-speed="10" class="pages text-center">
    <div class="parallax-overlay text-center">
        <h2 class="text-center">
            <span class="bigintro-light">Aplicativos</span>
        </h2>
        <iframe class="hidden-xs" src="http://player.vimeo.com/video/72393668" width="700" height="393" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

        <iframe class="visible-xs" src="http://player.vimeo.com/video/72393668" width="100%" height="auto" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</section>