<section id="portfolio" class="color-light text-center">
    <div class="divide40"></div>
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">
                <span class="bigintro">Portfolio</span>
            </h2>
        </div>
    </div>
    <div class="divide60"></div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div id="filters" class="text-center btn-group">
                <div  class="hidden-xs">
                    <a class="btn btn-lg btn-primary active" data-filter="*" href="#">Todos</a>
                    <a class="btn btn-lg btn-warning" data-filter=".projeto" href="#">Projetos</a>
                    <a class="btn btn-lg btn-success" data-filter=".aplicativo" href="#">Aplicativos</a>
                    <a class="btn btn-lg btn-danger" data-filter=".website" href="#">Websites</a>
                </div>
                <div class="visible-xs">
                    <select id="e1" class="form-control">
                        <option value="*">Todos</option>
                        <option value=".projeto">Projetos</option>
                        <option value=".aplicativo">Aplicativos</option>
                        <option value=".website">Websites</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="divide40"></div>
    <div class="container">
        <div id="filter-items" class="row">
            <div class="col xs-12 col-sm-4 aplicativo item">
                <div class="filter-content">
                    <img src="/img/site/gallery/alicerce.jpg" alt="" class="img-responsive" />
                    <div class="image-content">
                        <h4>Aplicativo Alicerce</h4>
                        <p class="hidden-xs hidden-sm">
                            Automação de Locação de Equipamentos para Construção
                        </p>
                        <a href="/img/site/gallery/alicerce.jpg" class="btn btn-sm btn-warning colorbox-button">Saiba Mais</a>
                    </div>
                </div>
            </div>
            <div class="col xs-12 col-sm-4 aplicativo item">
                <div class="filter-content">
                    <img src="/img/site/gallery/rodacms.jpg" alt="" class="img-responsive" />
                    <div class="image-content">
                        <h4>RoDa CMS</h4>
                        <p class="hidden-xs hidden-sm">
                            Gerenciador de CMS e Revistas Digitais.
                        </p>
                        <a href="/img/site/gallery/rodacms.jpg" class="btn btn-sm btn-warning colorbox-button">Saiba Mais</a>
                    </div>
                </div>
            </div>
            <div class="col xs-12 col-sm-4 website item">
                <div class="filter-content">
                    <img src="/img/site/gallery/rodablog.jpg" alt="" class="img-responsive" />
                    <div class="image-content">
                        <h4>RoDa Blog - Responsivo</h4>
                        <p class="hidden-xs hidden-sm">
                            Blog pessoal e Responsivo Light
                        </p>
                        <a href="/img/site/gallery/rodablog.jpg" class="btn btn-sm btn-warning colorbox-button">Saiba Mais</a>
                    </div>
                </div>
            </div>
            <div class="col xs-12 col-sm-4 projeto item">
                <div class="filter-content">
                    <img src="/img/site/gallery/publique.jpg" alt="" class="img-responsive" />
                    <div class="image-content">
                        <h4>Publique Anúncios Facebook</h4>
                        <p class="hidden-xs hidden-sm">
                            Organizador de Anúncios do Facebook.
                        </p>
                        <a href="/img/site/gallery/publique.jpg" class="btn btn-sm btn-warning colorbox-button">Saiba Mais</a>
                    </div>
                </div>
            </div>
            <div class="col xs-12 col-sm-4 website item">
                <div class="filter-content">
                    <img src="/img/site/gallery/thinlog.png" alt="" class="img-responsive" />
                    <div class="image-content">
                        <h4>ThinLog Logística</h4>
                        <p class="hidden-xs hidden-sm">
                            A ThinLog é uma empresa voltada para a otimização do transporte rodoviário de cargas em todo o Brasil
                        </p>
                        <a href="/img/site/gallery/thinlog.png" class="btn btn-sm btn-warning colorbox-button">Saiba Mais</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="divide60"></div>
</section>