<section id="signup-again" class="color-primary pattern text-center">
    <section class="container">
        <div class="divide20"></div>
        <div class="row">
            <div class="col-md-12">
                <h3 class="centered big call-to-action">
                    Deixe seu email para pedir um orçamento
                </h3>
            </div>
        </div>
        <div class="divide20"></div>
        <div class="row">
            <form class="form-inline centered" role="form">
                <div class="form-group">
                    <label class="sr-only" for="exampleInputEmail2">Endereço de Email</label>
                    <input type="email" class="form-control input-lg" id="exampleInputEmail2" placeholder="Digite seu endereço de email.">
                </div>
            </form>
        </div>
        <br/>
        <div class="row">
            <button type="submit" class="btn btn-warning btn-lg">Pedir Orçamento</button>
        </div>
        <div class="divide20"></div>
    </section>
</section>