<section class="color-danger social text-center">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Fique por dentro das novidades, me siga</h3>
                <i class="fa fa-twitter-square fa-2x darkred rm20 bm10"></i>
                <i class="fa fa-facebook-square fa-2x darkred rm20 bm10"></i>
                <i class="fa fa-linkedin-square fa-2x darkred rm20 bm10"></i>
                <i class="fa fa-youtube-square fa-2x darkred rm20 bm10"></i>
                <i class="fa fa-google-plus-square fa-2x darkred rm20 bm10"></i>
            </div>
        </div>
    </section>
</section>