<section id="team" class="color-light text-center">
    <div class="container">
        <div class="divide40"></div>
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center">
                    <span class="bigintro">A Equipe/span>
                </h2>
            </div>
        </div>
        <div class="divide60"></div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="team">
                    <img alt="" src="/img/site/img1.jpg">
                    <h3>Ruby Burrow</h3>
                    <h4>Production Manager</h4>
                    <p>I just want to argue I saw it chewing the orange peels I grow on my lawn, so I deleted it from my book.</p>
                    <a class="facebook" title="twitter" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" title="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="linkedin" title="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="team">
                    <img alt="" src="/img/site/img2.jpg">
                    <h3>Molly Debris</h3>
                    <h4>Assistant Buyer</h4>
                    <p>My waffle ate the banana last time. I saw it with my very eyes I tell you. I enjoy spinning chair on cheese.</p>
                    <a class="facebook" title="facebook" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" title="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="linkedin" title="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="team">
                    <img alt="" src="/img/site/img3.jpg">
                    <h3>Dave Jose</h3>
                    <h4>Brand Manager</h4>
                    <p>After eating that pie I just want to argue you may go smell the roses of the divine heaven.</p>
                    <a class="facebook" title="facebook" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" title="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="linkedin" title="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="team">
                    <img alt="" src="/img/site/img4.jpg">
                    <h3>Rachael Buffay</h3>
                    <h4>Design Head</h4>
                    <p>What a donkey your unicorn is. Give the penguin back its credit card right now. I just want to argue.</p>
                    <a class="facebook" title="facebook" href="#"><i class="fa fa-facebook"></i></a>
                    <a class="twitter" title="twitter" href="#"><i class="fa fa-twitter"></i></a>
                    <a class="linkedin" title="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
        </div>
        <div class="divide60"></div>
    </div>
</section>