<section id="parallax-2" data-type="background" data-speed="10" class="pages textcenter">
    <div class="parallax-overlay">
        <h2 class="text-center">
            <span class="bigintro-light">Depoimentos</span>
        </h2>
        <div id="myCarousel" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <div class="container">
                        <div class="carousel-caption">
                            <div class="row">
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot1.jpg" alt="headshot #1" />
                                    <h3>Jane Richards</h3>
                                    <p>"He found himself at first in a thoroughly European quarter, the houses having low fronts, and being adorned with verandas, beneath which he caught glimpses of neat peristyles. This quarter occupied, with its streets, squares, docks, and warehouses."</p>
                                    <h4>www.firstname.com</h4>
                                </div>
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot2.jpg" alt="headshot #2" />
                                    <h3>Shelly Doe</h3>
                                    <p>"The civil Emperor, before the Mikado, the spiritual Emperor, absorbed his office in his own. The Carnatic anchored at the quay near the custom-house, in the midst of a crow-fluidd of ships bearing the flags of all nations. Passepartout went."</p>
                                    <h4>www.secondname.com</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="container">
                        <div class="carousel-caption">
                            <div class="row">
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot3.jpg" alt="headshot #3" />
                                    <h3>Jim Doe</h3>
                                    <p>"He found himself at first in a thoroughly European quarter, the houses having low fronts, and being adorned with verandas, beneath which he caught glimpses of neat peristyles. This quarter occupied, with its streets, squares, docks, and warehouses."</p>
                                    <h4>www.thirdname.com</h4>
                                </div>
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot4.jpg" alt="headshot #4" />
                                    <h3>Kim Doe</h3>
                                    <p>"The civil Emperor, before the Mikado, the spiritual Emperor, absorbed his office in his own. The Carnatic anchored at the quay near the custom-house, in the midst of a crow-fluidd of ships bearing the flags of all nations. Passepartout went."</p>
                                    <h4>www.lastname.com</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="container">
                        <div class="carousel-caption">
                            <div class="row">
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot5.jpg" alt="headshot #4" />
                                    <h3>Liz Doe</h3>
                                    <p>"He found himself at first in a thoroughly European quarter, the houses having low fronts, and being adorned with verandas, beneath which he caught glimpses of neat peristyles. This quarter occupied, with its streets, squares, docks, and warehouses."</p>
                                    <h4>www.doefirst.com</h4>
                                </div>
                                <div class="circular col-md-6">
                                    <img src="/img/site/testimonials/headshot6.jpg" alt="headshot #5" />
                                    <h3>Nat Doe</h3>
                                    <p>"The civil Emperor, before the Mikado, the spiritual Emperor, absorbed his office in his own. The Carnatic anchored at the quay near the custom-house, in the midst of a crow-fluidd of ships bearing the flags of all nations. Passepartout went."</p>
                                    <h4>www.natgeo.com</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="fa fa-chevron-left fa-2x"></span></a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="fa fa-chevron-right fa-2x"></span></a>
        </div>
        <div class="divide85"></div>
    </div>
</section>