<section id="footer" class="color-light pattern">
    <div class="container">
        <div id="column-footer" class="row-fluid">
            <div class="col-sm-4">
                <h3>Saiba Mais</h3>
                <ul>
                    <li><a href="#">Como isso funciona?</a></li>
                    <li><a href="#">Qual o projeto ideal</a></li>
                    <li><a href="#">Depoimentos</a></li>
                    <li><a href="#">Meu Blog</a></li>
                </ul>
            </div>
            <div class="col-sm-4">
                <h3>Ajuda & Suporte</h3>
                <ul>
                    <li><a href="#">F.A.Q.</a></li>
                    <li><a href="#">Requerimento de Criação</a></li>
                    <li><a href="#">Termos de Uso</a></li>
                    <li><a href="#">Garantias e Prazos</a></li>
                </ul>
            </div>
            <div class="col-sm-4">
                <h3>Quem Sou?</h3>
                <ul>
                    <li><a href="#">Press</a></li>

                </ul>
            </div>
        </div>
    </div>
</section>