<section id="header" data-type="background" data-speed="10">
    <!-- OVERLAY -->
    <!-- <div class="overlay"> -->
    <div id="sidebar-collapse" class="sidebar-collapse btn visible-xs">
        <i class="fa fa-bars" data-icon2="fa fa-bars" data-icon1="fa fa-bars"></i>
    </div>
    <div class="divide60"></div>
    <div id="mobile-menu" class="list-group collapse text-center">
        <a href="#portfolio" class="list-group-item">Portfolio</a>
        <a href="#parallax-1" class="list-group-item">Aplicativos</a>
        <a href="#about" class="list-group-item">Quem Sou?</a>
        <a href="#features" class="list-group-item">Desenvolvimento</a>

        <a href="#contact" class="list-group-item">Contato</a>
        <a href="http://admin.rodrigodaniel.com.br" class="list-group-item external">Login</a>
    </div>

    <!-- HERO -->
    <div class="container-transparent text-center">
        <ul class="heronav left hidden-xs">
            <li><a href="#portfolio">Portfolio</a></li>
            <li><a href="#parallax-1">Aplicativos</a></li>
            <li><a href="#about">Quem Sou?</a></li>
        </ul>
        <ul class="heronav right hidden-xs">
            <li><a href="#features">Desenvolvimento</a></li>

            <li><a href="#contact">Contato</a></li>
            <li><a href="http://admin.rodrigodaniel.com.br" class="external">Login</a></li>
        </ul>
        <h1>
            <img src="/img/site/logo/logo.png" height="50" alt="logo name">
        </h1>
        <h1 class="page-title">Bem vindo à minha página pessoal.</h1>
        <h4 class="page-sub-title">Conheça meus trabalhos e projetos em desenvolvimento
            <br>

        </h4>
        <div class="showcase">
            <a class="btn btn-warning btn-lg hidden-xs" href="#portfolio">Saiba Mais &nbsp;&nbsp;<i class="fa fa-play"></i></a>
            <a class="btn btn-warning btn-sm visible-xs" href="#portfolio">Saiba Mais &nbsp;&nbsp;<i class="fa fa-play"></i></a>
        </div>
    </div>
    <!--/HERO -->
    <!-- </div> -->
    <!--/OVERLAY -->
</section>