<div id="nav-bar">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-md-4">
                <div class="logo" >
                    <a href="/"><img src="/img/site/logo/logo.png" height="40" alt="logo name"/></a>
                </div>
            </div>
            <div class="col-sm-9 col-md-8">
                <nav id="fixed-top-navigation">
                    <ul class="list-inline pull-right">
                        <li><a href="#portfolio">Portfolio</a></li>
                        <li><a href="#parallax-1">Aplicativos</a></li>

                        <li><a href="#about">Quem Sou?</a></li>
                        <li><a href="#features">Desenvolvimento</a></li>
                        <li><a href="#contact">Contato</a></li>
                        <li><a href="http://admin.rodrigodaniel.com.br" class="external">Login</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>